# Generated by Django 5.0.6 on 2024-06-15 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('appointmentTime', models.DateTimeField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('dateOfBirth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('medic', models.CharField(max_length=200)),
                ('personalNumericCode', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Personal ID must be numeric.', regex='^\\d+$')])),
                ('phoneNumber', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Please enter a valid phone mumber', regex='^+?4?\\d{10,12}')])),
                ('typeOfService', models.CharField(max_length=300)),
            ],
        ),
    ]
