# Generated by Django 5.0.6 on 2024-06-16 07:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phoneNumber',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Please enter a valid phone mumber', regex='^\\+?4?\\d{10,12}$')]),
        ),
    ]
