# Generated by Django 5.0.6 on 2024-06-18 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_booking_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='appointmentTime',
            new_name='appointmentDateAndTime',
        ),
    ]
